<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once 'predlozak/head.php'; ?>
  </head>
  <body>
    <div class="grid-container">
      <?php require_once 'predlozak/izbornik.php' ?>
      <!-- Početak tijela -->
      <div class="grid-x">
        <div class="large-12 small-12 columns">
          <div class="callout" style="min-height: 400px;"> 
            
          Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
<br> <br> <br>

          <?php 
    $fib=[1,1];
    $sum=0;
    $a=1;
    $b=1;
    $c=1;
    while ($c <= 4000000){
        
        $c=$a+$b;
        $a=$b;
        $b=$c;
        if($c<=4000000)
        $fib[]=$c;
        if($c%2===0) $sum+=$c;
    };




    echo $sum;
    echo '<pre>';
    print_r($fib);
    echo '</pre>';
 ?>

          </div>
        </div>
      </div>
      <!-- Kraj tijela -->
      <?php require_once 'predlozak/podnozje.php' ?>
    </div>
    <?php require_once 'predlozak/skripte.php' ?>
  </body>
</html>



